INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL GHIMIRE', 'SARITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASHYAL', 'DHURBA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('RAJTHALA', 'NANICHHORI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAKURI', 'SAKUN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAH', 'PRIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'KIYARA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('MEHTA', 'JATIN');
INSERT INTO travellers (last_name, first_name) VALUES ('MEHTA', 'JATIN');
INSERT INTO travellers (last_name, first_name) VALUES ('AMATYA', 'CRISJIN');
INSERT INTO travellers (last_name, first_name) VALUES ('MASKEY', 'JASMINE K C');
INSERT INTO travellers (last_name, first_name) VALUES ('SAH', 'PRIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'KIYARA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'BHARATI');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'BIKASH SINGH');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'ROSE');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'SASHA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPABANIYA', 'SARITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'REHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL SUBEDI', 'BHAWANI');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'POOJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'REYANSH PUJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('REGMI', 'BHIMA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'GYANENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SANGYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SHREYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SUBIGYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KUNWAR BOHARA', 'SABINA');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'ANJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'AAGAT');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'PRASAMSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SUVASH');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MADAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATUN', 'NAJRANA');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AIZAN ALAM');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AABAN ALI');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NIRAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SARASWATI');
INSERT INTO travellers (last_name, first_name) VALUES ('SINGH', 'TUSHANT MAN');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'ALAM GIR');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUJEL', 'SURAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('JAMES', 'CARLA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHURTYAL', 'BIPANA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHURTYAL', 'BIPANA');
INSERT INTO travellers (last_name, first_name) VALUES ('SINGH', 'TUSHANT MAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'MALATI');
INSERT INTO travellers (last_name, first_name) VALUES ('RAJTHALA', 'SAJITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUJEL', 'SURAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'DILIP');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'YUBAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAYEMI', 'PURAN BHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'RAJESH');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL', 'SADIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMSINA', 'KHILENDRA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'RUPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('ZAMORA', 'HERNANE MONTOYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BYANJU', 'SAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'DENISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHANAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERPA', 'PASANG');
INSERT INTO travellers (last_name, first_name) VALUES ('ANSARI', 'TAYSIR');
INSERT INTO travellers (last_name, first_name) VALUES ('ANSARI', 'TARIQ ANWAR');
INSERT INTO travellers (last_name, first_name) VALUES ('KSHETRI', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('AYER', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('AWALE', 'DATI');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'GYANENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SUBIGYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KUNWAR BOHARA', 'SABINA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SANGYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'SHREYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'KHADGA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TEJ BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'AAGAT');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'ANJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHI', 'SAMIA ISLAM');
INSERT INTO travellers (last_name, first_name) VALUES ('PARVEZ', 'SHAHIN MAHMUD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERPA', 'PASANG');
INSERT INTO travellers (last_name, first_name) VALUES ('SAMBAHAMPHE', 'YAMBHAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERCHAN', 'INDRA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'RAJESH');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'RAJESH');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHAT', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SIJAPATI', 'AYESHA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'DILIP');
INSERT INTO travellers (last_name, first_name) VALUES ('KSHETRI', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'KHADGA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TEJ BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'MOHAN BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SUMIT');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATUN', 'NARJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AIZAN ALAM');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AABAN ALI');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AABAN ALI');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATUN', 'NAJRANA');
INSERT INTO travellers (last_name, first_name) VALUES ('MIKRANI', 'AIZAN ALAM');
INSERT INTO travellers (last_name, first_name) VALUES ('NAGARKOTI', 'SHYARON');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'KALI');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'SITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'RAM HARI');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'SARASWOTI');
INSERT INTO travellers (last_name, first_name) VALUES ('KSHETRI', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SUVASH');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'PRASAMSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PARAJULI', 'SANJIB');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KSHETRI', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'KRISHTINA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'SUMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'SUJATA UPADHYAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'UMESH BDR');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SANDHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KOJU', 'DEEPAK');
INSERT INTO travellers (last_name, first_name) VALUES ('SINKEMANA', 'BINA');
INSERT INTO travellers (last_name, first_name) VALUES ('KOJU', 'DIVIANA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('HAMAL', 'NISCHAL BIKRAM');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERPA', 'PEMA');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'YUBAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAYEMI', 'PURAN BHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('KSHETRI', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA PANDEY', 'SHOVA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'BINDU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHARALSAPKOTA', 'PARIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('HAMAL', 'RAMU');
INSERT INTO travellers (last_name, first_name) VALUES ('HAMAL', 'NISCHAL BIKRAM');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SOFIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'POOJA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'ANITA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SAKUNTALA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'RABINDRA KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('REGMI', 'MOHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'RASHMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('AGRAHARI', 'MAHESH');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'ANUPAM');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL', 'NITA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'SULAV');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERPA', 'DOMA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MEERA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'OM PRAKASH');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'KRISA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI KHATIWADA', 'SARITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'KASYA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHAUDHARY', 'UMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL', 'KAJOL');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'SAHANSHILA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAI', 'RAM CHANDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DURGA MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'BIJAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHAULAGAIN', 'BISHOW BHUSHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('CHAULAGAIN', 'BISMARK');
INSERT INTO travellers (last_name, first_name) VALUES ('CHAULAGAIN', 'SYLBI');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'ARVIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'ROHIT');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'SIRJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'ACHYATA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA PANDEY', 'SHOVA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SUSHMA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MAHESH PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MAYANK');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NABARAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'KANCHI');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'SRIYANK');
INSERT INTO travellers (last_name, first_name) VALUES ('KOIRALA', 'SIRJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'SAHANSHILA');
INSERT INTO travellers (last_name, first_name) VALUES ('BAJRACHARYA', 'SUJITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'SAMEER');
INSERT INTO travellers (last_name, first_name) VALUES ('SIMKHADA', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'SAMEER');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'KHADGA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TEJ BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'AAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'RAMA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SAMAR BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TIRTHA BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TIRTHA BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KIRAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SANTA MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SUYORA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAI', 'JYOTI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SUYANA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAI', 'TEJU MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'ACHYATA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA CHHETRI', 'SUSHILA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'MANOJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAKYA', 'JYOTSANA');
INSERT INTO travellers (last_name, first_name) VALUES ('TANDAN', 'RAJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('TANDAN', 'RAYDEN SINGH');
INSERT INTO travellers (last_name, first_name) VALUES ('LAWAT', 'PRASHANTI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERPA', 'PEMA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'SITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANERU', 'PUKAR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA PANERU', 'ANJILA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'MANOJ');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'NISHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('LOHANI', 'ANMOL');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'PRASHANT');
INSERT INTO travellers (last_name, first_name) VALUES ('YADAV', 'DIPESH KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SANTA MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'KANCHI');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NABARAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'AJUDHA');
INSERT INTO travellers (last_name, first_name) VALUES ('GUYALA', 'MATHEW FRANCO JR');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'PINU');
INSERT INTO travellers (last_name, first_name) VALUES ('MALLA', 'SHEKHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'RAJESH');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'DEEPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SMARIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'SUVECHHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SHRYNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SUDEEP');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SARYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'BIPUL');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SUJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUTAM', 'INDIRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA POUDYAL', 'SMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDYAL', 'AAVIANA');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDYAL', 'AAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDYAL', 'AJAY');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'ALLIUM ARIN');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SHIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'ARWYN ACE');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'SAMIR');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'ASMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'AAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'NARAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'BIMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'AAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'SAUGAT');
INSERT INTO travellers (last_name, first_name) VALUES ('NAIDE HEWA', 'NADUN NETHTHIMA SILVA');
INSERT INTO travellers (last_name, first_name) VALUES ('BAN', 'MUKTI KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('BAN', 'PADAM BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BAN', 'PHURI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'ANUJ BIKRAM');
INSERT INTO travellers (last_name, first_name) VALUES ('PRASAI', 'AADITYA');
INSERT INTO travellers (last_name, first_name) VALUES ('PRASAI', 'DIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SIGDEL', 'PRATIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'DILIP RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAI', 'DEEPLOVE');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'GYANENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARISHARMA', 'DIPIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'AYSA');
INSERT INTO travellers (last_name, first_name) VALUES ('SILWAL', 'RAM KRISHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'ANUPAM');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL', 'NITA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'SUSHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'DILIP');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'PRAWESH');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUTAM', 'SIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL', 'MANISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIWARI', 'RAJ DHARMA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SWESHA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'JOHN');
INSERT INTO travellers (last_name, first_name) VALUES ('RANA', 'KABITA');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'BINOD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUBASH');
INSERT INTO travellers (last_name, first_name) VALUES ('MAINALI', 'LEENA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SATHVIK');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUVANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'SURENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'SAMJHANA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'POOJA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUYAL', 'SUDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'ANUKUL');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'MIN PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUTAM', 'SHANTI KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'DILIP');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'PINU');
INSERT INTO travellers (last_name, first_name) VALUES ('MALLA', 'SHEKHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('ZAMORA', 'HERNANE MONTOYA');
INSERT INTO travellers (last_name, first_name) VALUES ('VILLEGAS', 'DANILO ESTEBAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BUDHATHOKI', 'NISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'NISHA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUTAM PATHAK', 'RAMA');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'CHIRAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'KRISA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI KHATIWADA', 'SARITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'KASYA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA NEPAL', 'SUSHMA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'NABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('RISAL', 'ROJINA');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SHAARVI');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SANDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'ASMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA NEPAL', 'SUSHMA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI CHHETRI', 'SAMIR');
INSERT INTO travellers (last_name, first_name) VALUES ('KAFLE', 'HEM RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'PARBATI');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MUKUNDA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SANJAY');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'SUJIT');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'PUSHPA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SABBU');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SUBHAM');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'LENIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'STALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('DANGOL', 'KISA MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'CHANDRA KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'PRANISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('KAFLE', 'ASHOK');
INSERT INTO travellers (last_name, first_name) VALUES ('GUYALA', 'MATHEW FRANCO JR');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'PRADIP');
INSERT INTO travellers (last_name, first_name) VALUES ('BUDHATHOKI', 'RAJIT');
INSERT INTO travellers (last_name, first_name) VALUES ('BUDHATHOKI', 'SAMRAT');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'BINOD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIKASH');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIANKA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIKASH');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'NISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('NEPAL', 'DEYA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL UPADHAYAY', 'BISHNU');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL UPADHAYAY', 'BISHNU');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'SUNITA');
INSERT INTO travellers (last_name, first_name) VALUES ('RIJAL', 'CHANDRA BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'JAMUNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'RAMA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SUSILA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'YOG MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAGAR', 'GAUTAM THAPA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'YASODHA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'LENIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'LENIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAKURI', 'SAKUN');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMSAL', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMSAL', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SARINA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTA', 'BISHNU');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMA GHALAN', 'SUNIL');
INSERT INTO travellers (last_name, first_name) VALUES ('NAPIT', 'MENUKA');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'RAJANI');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAY', 'SABITRI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'BISHAL');
INSERT INTO travellers (last_name, first_name) VALUES ('SIJAPATI', 'AYESHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANERU', 'PUKAR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA PANERU', 'ANJILA');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'TILAK BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'GYANU DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'MINA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'OM BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('BAIDYA', 'ROMANY');
INSERT INTO travellers (last_name, first_name) VALUES ('KC MASKEY', 'BHAGYASHREE');
INSERT INTO travellers (last_name, first_name) VALUES ('MASKEY', 'JASMINE K C');
INSERT INTO travellers (last_name, first_name) VALUES ('AMATYA', 'CRISJIN');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'SITA RAM');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDEY', 'CHAHANA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPALIYA', 'UMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('BANIYA', 'KALI');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'LAL PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('HUMAGAIN', 'MANISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SUREKHA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG TAMANG', 'SAMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'BIR BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'NORJIN');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'HARI PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('SIWAKOTI', 'SHREE PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SANGITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'SHRISTI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'INDIRA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ISHWAR LAL');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'NAR DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('JAYASUNDARA KAPURALALAGE', 'AMARAWATHIE');
INSERT INTO travellers (last_name, first_name) VALUES ('RATNAYAKE', 'MANJULA PRIYADARSHANI');
INSERT INTO travellers (last_name, first_name) VALUES ('RIJAL', 'RAVI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'PRATIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('RIJAL', 'RAKSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAY', 'SABITRI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SAKUNTALA DEVEE');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'BAISNABI');
INSERT INTO travellers (last_name, first_name) VALUES ('BOHARA', 'RUPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('KUNWAR', 'NISCHAL');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'LAL PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('LAKAI', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('LAKAI', 'SARITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BALAMI', 'SABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('BALAMI', 'SABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMSAL', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMSAL', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'SUVECHHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SARYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SHRYNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'SUDEEP');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUJEL', 'SURAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BAJRACHARYA', 'PADAM BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'KIRAN KRISHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SATYA NARAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SUDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'NIRAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMA', 'DHRUBA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('RAYAMAJHI', 'SHANTI BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAKYA', 'SHIBIR RATNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAKYA', 'SUBIN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'ARPAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SURAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'ROJINA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSHAL', 'SURAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSHAL', 'RANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SARMILA');
INSERT INTO travellers (last_name, first_name) VALUES ('SWAR', 'DAMBAR BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SARMILA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SUDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('BAJRACHARYA', 'PADAM BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'KIRAN KRISHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SATYA NARAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'ARPAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAKYA', 'SUBIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SURAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SUDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'NIRAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMA', 'DHRUBA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('RAYAMAJHI', 'SHANTI BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAKYA', 'SHIBIR RATNA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'MADHAV');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SAIMON');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SAMUEL');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SUNITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSAL', 'BIJAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('DULAL', 'BISHNU MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('DULAL', 'PURNA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSAL', 'PRABATI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSAL', 'PARBATI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'MURARI');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SITA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSAL', 'PARBATI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('KOIRALA', 'RABINDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'MEENAKCHHI');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIANKA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIKASH');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'NISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'IHRAH');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KAMALA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'MIN BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'MADHAV');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI', 'PRADEEP');
INSERT INTO travellers (last_name, first_name) VALUES ('RANABHAT', 'SONIA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RAJU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('BYANJU', 'SAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHAISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'DENISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHANAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'PRAMILA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'DURGA');
INSERT INTO travellers (last_name, first_name) VALUES ('SIWAKOTI', 'PRAJAPATI');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'ROSTIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'KERINA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHANTYAL', 'INDRA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('STOBBS', 'DAVID');
INSERT INTO travellers (last_name, first_name) VALUES ('STOBBS', 'SEETHA SUNITH');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADGI', 'DIWAS');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERCHAN', 'PUKAR KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA PAUDEL', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI POKHREL', 'NAMRATA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL UPADHAYAY', 'BISHNU');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'DANISH');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'RHYTHM');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'ZENITH');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA PAUDEL', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'SURESH');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BRANSON');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'PRINSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL BARAL', 'PABITRA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BHAGABATI');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'DEVI PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('TITUNG', 'OSHIN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BISHNU PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'AARAMBHA');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAY', 'SABITRI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('NIURE', 'DILAKUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('NIURE', 'PRITHI LAL');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'JEETENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('JOSHI', 'MUKESH RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('TITUNG', 'OSHIN');
INSERT INTO travellers (last_name, first_name) VALUES ('TITUNG', 'OSHIN');
INSERT INTO travellers (last_name, first_name) VALUES ('SRIS MAGAR', 'JUNA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SABITRI');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'POOJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'REYANSH PUJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SIWAKOTI', 'CHANDRAKALA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'RAJ GOLE');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'SHREEDHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('OJHA', 'KARISHMA');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'DURGA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'SARITA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('NEWAR ALIAS SHRESTHA', 'PURNA LAL');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'NANU MAYA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('SHERCHAN', 'INDRA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('JAMES', 'CARLA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'KAMAL MR');
INSERT INTO travellers (last_name, first_name) VALUES ('GELAL', 'SAMYOG MR');
INSERT INTO travellers (last_name, first_name) VALUES ('RAI', 'SAMIR MR');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'CHANDRA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SHOVADEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'TIRTHA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'BINOD KUMAR MR');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SABITRI');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'DIPTI');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'DIPTI');
INSERT INTO travellers (last_name, first_name) VALUES ('DULAL', 'ROSHAN PRASAD MR');
INSERT INTO travellers (last_name, first_name) VALUES ('PAKHRIN', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('PUN MAGAR', 'SAMBHABIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'REKHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'DEEPIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('JAMKATEL', 'PRALAD');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'APEKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAI', 'PRASHANT');
INSERT INTO travellers (last_name, first_name) VALUES ('CHOUHAN', 'NAWARAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('KRAKI', 'PRALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'PRALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHARJAN', 'BISHESH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MILAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'PRATIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SARAHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAHA MAGAR', 'BHIM MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAHA MAGAR', 'NANDLAL');
INSERT INTO travellers (last_name, first_name) VALUES ('SILWAL', 'RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SILWAL', 'BHAGABATI');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL', 'GARIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'YASODHA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA MAGAR', 'GAUTAM');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'MOHAN BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'GANGA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RAJU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('PARAJULI', 'YOGESH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMALSINA', 'KIRAN MR');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'SASHANK');
INSERT INTO travellers (last_name, first_name) VALUES ('MAHATO', 'AASISH');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'PRALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHALE', 'SANAM MR');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'MALA');
INSERT INTO travellers (last_name, first_name) VALUES ('RUPAKHETI', 'BIJAYA MR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHIWAKOTI', 'KARUNA');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'PUNAM');
INSERT INTO travellers (last_name, first_name) VALUES ('KUNWAR CHHETRI', 'PRADIP');
INSERT INTO travellers (last_name, first_name) VALUES ('BUDHATHOKI', 'SUSHMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('SEDHAI', 'RUPESH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'UJJWAL MR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'ASMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('ALE MAGAR', 'SUDESHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'MUSKAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KAFLE', 'SUJITA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'ASMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'NAWA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'BIKASH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMA', 'USHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PUN', 'NELSON');
INSERT INTO travellers (last_name, first_name) VALUES ('RAWAL', 'ROHAN MR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SUREKHA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASHYAL', 'SASHANKA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MRYNAL');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MUKUNDA');
INSERT INTO travellers (last_name, first_name) VALUES ('TANDUKAR', 'SUSMITA');
INSERT INTO travellers (last_name, first_name) VALUES ('NAIDE HEWA', 'NADUN NETHTHIMA SILVA');
INSERT INTO travellers (last_name, first_name) VALUES ('ANGDAMBE', 'RUPEN LIMBU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'CHANDRA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAMI', 'KAILASH SINGH');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MUKUNDA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'PANKAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('BARAL', 'SOVIT');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUBASH');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BISHNU PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BRANSON');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'PRINSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL BARAL', 'PABITRA');
INSERT INTO travellers (last_name, first_name) VALUES ('KATHET', 'NAVRAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA KATHET', 'SABITRI');
INSERT INTO travellers (last_name, first_name) VALUES ('KATHET', 'NYSA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SITA');
INSERT INTO travellers (last_name, first_name) VALUES ('KOIRALA SHRESTHA', 'ANURADHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'AAVIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHRUTI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAH', 'PRIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAH', 'KIYARA');
INSERT INTO travellers (last_name, first_name) VALUES ('POUDEL SUBEDI', 'BHAWANI');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'REYANSH PUJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BISHNU PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('ANSARI', 'NIKHAT');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SOFIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SOFIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'SHASHI KALA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KIRAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'YASH RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'SHOVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KARKI', 'SURENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTA', 'ALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL KANDEL', 'MANJU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI', 'BABITA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAKURI', 'SAKUN');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MILAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'PRATIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SARAHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MILAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'PRATIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'KALYAN BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('DEVKOTA', 'ARCHER');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MANARAM');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'MITHU');
INSERT INTO travellers (last_name, first_name) VALUES ('YADAV', 'DIPESH KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'PRAPTI');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'PRISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MADHAV');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SITA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KIRAN');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'RUPA');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'MURARI');
INSERT INTO travellers (last_name, first_name) VALUES ('MISHRA', 'SITA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MADHAV');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SITA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('FATAI', 'LEILANI PRINCESS AIESHA HONEY');
INSERT INTO travellers (last_name, first_name) VALUES ('FATAI', 'LUPE LAUREN FATAI');
INSERT INTO travellers (last_name, first_name) VALUES ('LEMALU', 'TAREK MASOOD');
INSERT INTO travellers (last_name, first_name) VALUES ('LEMALU', 'AALIYAN HONEY');
INSERT INTO travellers (last_name, first_name) VALUES ('LEMALU', 'AALIYAH HONEY');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'NIMUNG');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'ABHISEK');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'DURGA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAJBANSHI', 'DIKSON');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'AAYUSH');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'AMISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE BHATTARAI', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC MASKEY', 'BHAGYASHREE');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'ABHYANT BIR SINGH');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'AMOGH');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'RAM CHANDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'PUSHPA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'SHUBHAM');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SAGAR');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'ANUSANDHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KUMWAR', 'UDIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('KUNWAR', 'UDIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'CHET KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SIWAKOTI', 'PRAJAPATI');
INSERT INTO travellers (last_name, first_name) VALUES ('BASHYAL', 'DHURBA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('BASHYAL', 'RADHIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL BASHYAL', 'BHAGWATI');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SHIKSHYA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'ALLIUM ARIN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'ARWYN');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SUSHIL');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SUDHARSHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'AAYUSH');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'PRAJWAL');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SRIJAY');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'AMRITA');
INSERT INTO travellers (last_name, first_name) VALUES ('DANGORIYA THARU', 'RAMU');
INSERT INTO travellers (last_name, first_name) VALUES ('CHHETRI', 'SUJATA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SAPANA');
INSERT INTO travellers (last_name, first_name) VALUES ('BK', 'ROHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SANDHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'SUBASH');
INSERT INTO travellers (last_name, first_name) VALUES ('PUDASAINI', 'SANTOSH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('DANGORIYA THARU', 'RAMU');
INSERT INTO travellers (last_name, first_name) VALUES ('DANGORIYA THARU', 'RAMU');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'GANGA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'RUBY');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SUSAN KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'RUDRAKSH KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SARTHAK KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SUBARNA KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'PRATIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'NOAH');
INSERT INTO travellers (last_name, first_name) VALUES ('FATAI', 'LUPE LAUREN FATAI');
INSERT INTO travellers (last_name, first_name) VALUES ('LEMALU', 'TAREK MASOOD');
INSERT INTO travellers (last_name, first_name) VALUES ('LEMALU', 'AALIYAH HONEY');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROJAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAMI', 'KAILASH SINGH');
INSERT INTO travellers (last_name, first_name) VALUES ('BALAGUER PRAT', 'MARIA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SNEHA');
INSERT INTO travellers (last_name, first_name) VALUES ('MOHD SARIP', 'HABIBAH');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMSINA', 'KHILENDRA RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('PADHYANI', 'TULSI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'AMRITA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SRIJAY');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SNEHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SNEHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SNEHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PRASAI', 'CHANDRAKALA');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'GHANASHYAM');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'SAUGAT');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'GANGA');
INSERT INTO travellers (last_name, first_name) VALUES ('SIMKHADA', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KISHOR');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KIYANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'URMILA');
INSERT INTO travellers (last_name, first_name) VALUES ('ROKAYA', 'URMILA');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'ANUPAM');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'ANUPAM');
INSERT INTO travellers (last_name, first_name) VALUES ('BYANJU', 'SAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHAISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'DENISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHANAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MUKUNDA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHALE', 'KHUSHBOO');
INSERT INTO travellers (last_name, first_name) VALUES ('GHALE', 'KHUSHBOO');
INSERT INTO travellers (last_name, first_name) VALUES ('MEDIANA', 'DOMINGO');
INSERT INTO travellers (last_name, first_name) VALUES ('MONTERON', 'ARNEL');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SAPANA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'CHHALI MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA MAGAR', 'KEHAR SING');
INSERT INTO travellers (last_name, first_name) VALUES ('BUDHA', 'SRIJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('DANGI', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DHAN LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'GANGA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RAJU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'RADHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'RAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SIMKHADA', 'SARU');
INSERT INTO travellers (last_name, first_name) VALUES ('LAMA', 'BATULI');
INSERT INTO travellers (last_name, first_name) VALUES ('NAPIT', 'MAHIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SHANTA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'PRAJWAL');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'AMRITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANERU', 'PUKAR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA CHHETRI RIJAL', 'SITA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('GAURA', 'PRASAI KOIRALA');
INSERT INTO travellers (last_name, first_name) VALUES ('JOSHI', 'MUKESH RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('PRADHAN', 'RUBY');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DIPIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('NAIDE HEWA', 'NADUN NETHTHIMA SILVA');
INSERT INTO travellers (last_name, first_name) VALUES ('NAIDE HEWA', 'DEVIN TINUKA SILVA');
INSERT INTO travellers (last_name, first_name) VALUES ('NAIDE HEWA', 'NADUN NETHTHIMA');
INSERT INTO travellers (last_name, first_name) VALUES ('WEERARATHNA', 'ESMEE SRIYANIE');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'RADHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANDIT', 'RAJ KUMAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'JAMUNADEVI MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHRUTI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHRUTI');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KATHET', 'NAVRAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('KATHET', 'NYSA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA KATHET', 'SABITRI');
INSERT INTO travellers (last_name, first_name) VALUES ('CHITRAKAR', 'MOUSAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHEESHAM');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHALE', 'KHUSHBOO');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'DURGA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'GHANASHYAM');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'RAM HARI');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'SARASWOTI');
INSERT INTO travellers (last_name, first_name) VALUES ('KOIRALA', 'RABINDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SATHVIK');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUBASH');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUVANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('MAINALI', 'LEENA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'BIPIN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'KUSHMA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'YOGENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'AMISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SAMSUHANG', 'RUPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('KAFLE', 'SUJITA');
INSERT INTO travellers (last_name, first_name) VALUES ('KC', 'NABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('OLI', 'SABINA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'RITU');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'REBECCA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'REYANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'ROBIN');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'MOHAN BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('JOSHI', 'RICHA');
INSERT INTO travellers (last_name, first_name) VALUES ('LIMBU', 'BISHNU KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'URJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'INARA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'IVAAN RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SABIV');
INSERT INTO travellers (last_name, first_name) VALUES ('PANTHA', 'KRITI');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BISHNU PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SUSMA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SHIVA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SUSMA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA DANAI', 'SALINA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIKASH');
INSERT INTO travellers (last_name, first_name) VALUES ('UPADHYAYA', 'BIJAYA PAUDEL');
INSERT INTO travellers (last_name, first_name) VALUES ('DEVKOTA', 'KRISHNA PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('DEVKOTA', 'PARBATI');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'INDU');
INSERT INTO travellers (last_name, first_name) VALUES ('DEVKOTA', 'IANA');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'DIYAAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI', 'TIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('NIURE SAPKOTA', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('WONTA', 'SABITRI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'JAMUNA');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SUPRINSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('MALLA', 'BASANTA MR');
INSERT INTO travellers (last_name, first_name) VALUES ('MAKAJU', 'JANARDAN');
INSERT INTO travellers (last_name, first_name) VALUES ('MAKAJU', 'SAKILA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('MARAHATTA', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('YEH', 'YU CHU');
INSERT INTO travellers (last_name, first_name) VALUES ('MARAHATTA', 'ATHENA');
INSERT INTO travellers (last_name, first_name) VALUES ('MARAHATTA', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('YEH', 'YU HUA');
INSERT INTO travellers (last_name, first_name) VALUES ('YEH', 'YU HUA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'ROBIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'LAXMI');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'UMA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'RADHA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHUSAL', 'PARBATI DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ISHUPTA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ANKIT');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ANYA');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'SUJATA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'RIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'TULMAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI', 'ROSHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAMBAHAMPHE', 'YAMBHAMI');
INSERT INTO travellers (last_name, first_name) VALUES ('PARAJULI', 'PRATIKSHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('CHELVAKUMARAN', 'PRIYATHAKSHANI');
INSERT INTO travellers (last_name, first_name) VALUES ('CHELVAKUMARAN', 'SRI VEENA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANERU', 'PUKAR');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA PANERU', 'ANJILA');
INSERT INTO travellers (last_name, first_name) VALUES ('PANERU', 'AAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA CHHETRI RIJAL', 'SITA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('SILWAL', 'RAM KRISHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'ASHOK');
INSERT INTO travellers (last_name, first_name) VALUES ('YADAV', 'SHILU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'ABHIMAAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'DILIP');
INSERT INTO travellers (last_name, first_name) VALUES ('NEPAL', 'ALIJA');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'DINESH');
INSERT INTO travellers (last_name, first_name) VALUES ('BISTA', 'SUMIT');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('NEPALI', 'SURYA BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'DURGA PARSAD');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'LENIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'NIMUNG');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'STALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('CHAUDHARY', 'DIPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('TABBAH', 'FOUAD');
INSERT INTO travellers (last_name, first_name) VALUES ('TABBAH', 'FOUAD');
INSERT INTO travellers (last_name, first_name) VALUES ('TABBAH', 'FOUAD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'RITU');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'REBECCA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'REYANSH');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMRAKAR', 'ROBIN');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTA', 'BISHNU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'KAUSHILA MS');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA ACHARYA', 'AMRIT PRASAD MR');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'AVIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('ACHARYA', 'ADHVIK');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MANILA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NAMRATA');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'DANISH');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHREL', 'KHUSI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'RITA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'LENIN');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'SUMAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SRIS MAGAR', 'JUNA');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMANG', 'ROSHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('REGMI', 'JAGAT MR');
INSERT INTO travellers (last_name, first_name) VALUES ('NEPAL', 'HEM PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'RAM CHANDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'SABITRI');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'MADAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GHARTI MAGAR', 'LAL KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('PAIJA', 'JENISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('PAIJA', 'JIT BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('NIURE', 'DILA KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('NIURE', 'PRITHI LAL');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'BHAGABATI');
INSERT INTO travellers (last_name, first_name) VALUES ('ARYAL', 'DEVI PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MANILA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('REGMI', 'JAGAT MR');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'SUBASH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'SHREEDHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('INTHUSEGARAM', 'CHELVAKUMARAN');
INSERT INTO travellers (last_name, first_name) VALUES ('INTHUSEGARAM', 'CHELVAKUMARAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'PURNAKALA');
INSERT INTO travellers (last_name, first_name) VALUES ('KANDEL', 'SARASWATI');
INSERT INTO travellers (last_name, first_name) VALUES ('YADAV', 'KRITIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'RISHI KESH');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ROMI');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHARELSUBEDI', 'AMRITA');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'MADHU');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'AARUSI (CH- 5Y)');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'KRISAM (CH - 2Y)');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'SHREEDHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'INDIRA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ISWAR LAL');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL KANDEL', 'MANJU');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'BABU RAM');
INSERT INTO travellers (last_name, first_name) VALUES ('RANA', 'AYAAN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'SARIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('MASKI', 'SHAKTI');
INSERT INTO travellers (last_name, first_name) VALUES ('PUDASAINI', 'SUSHILA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMALSINA', 'SANTOSH');
INSERT INTO travellers (last_name, first_name) VALUES ('TAMALSINA', 'SHIVANK RAZ');
INSERT INTO travellers (last_name, first_name) VALUES ('PUDASAINI', 'RAMA');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMALSINA', 'SANNANI');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'HOM NARAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'MAYA DEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA', 'SUJIT RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA', 'SUYOG RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA SHRESTHA', 'SUJATA');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA SHRESTHA', 'SUJATA');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA', 'SUYANDEE');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA', 'SUYANDEE');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA SHRESTHA', 'SUJATA');
INSERT INTO travellers (last_name, first_name) VALUES ('ONTA', 'SUYANDEE');
INSERT INTO travellers (last_name, first_name) VALUES ('SHIWAKOTI', 'DEVI MAIYA');
INSERT INTO travellers (last_name, first_name) VALUES ('RAUT', 'SHANKAR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'SACHIN MR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'SHREEDHAR');
INSERT INTO travellers (last_name, first_name) VALUES ('PUDASAINI', 'SUJIT');
INSERT INTO travellers (last_name, first_name) VALUES ('PADAL', 'DEPAK RAJ MR');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'EDWIN');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'EVAN');
INSERT INTO travellers (last_name, first_name) VALUES ('PATHAK', 'SACHIN');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'KULINA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SANDHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MANOJ');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'EVAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SUBEDI', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NIRUSHA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'NISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'BIJENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'SAPANA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTA', 'AMRITA');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'SULAV');
INSERT INTO travellers (last_name, first_name) VALUES ('DHAKAL', 'SUNITA');
INSERT INTO travellers (last_name, first_name) VALUES ('PARAJULI', 'BADRI MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('KHAREL', 'SUBISHNA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'BIJENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'BIJENDRA');
INSERT INTO travellers (last_name, first_name) VALUES ('PUDASAINI', 'RAMA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHANDARI', 'ANITA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'ANISHA');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAHI', 'BAL BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHAHI', 'PABITRA');
INSERT INTO travellers (last_name, first_name) VALUES ('GHIMIRE', 'SAMRIDDHI');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'NIRMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RABIN');
INSERT INTO travellers (last_name, first_name) VALUES ('MANANDHAR', 'RAMESH');
INSERT INTO travellers (last_name, first_name) VALUES ('EVELYN TSZ PING', 'CHEUNG');
INSERT INTO travellers (last_name, first_name) VALUES ('SHRESTHA', 'JAMUNADEVI');
INSERT INTO travellers (last_name, first_name) VALUES ('DUWADEE', 'AYUSHREE');
INSERT INTO travellers (last_name, first_name) VALUES ('GIRI', 'GANGA');
INSERT INTO travellers (last_name, first_name) VALUES ('GIRI', 'KAMAL RAJ');
INSERT INTO travellers (last_name, first_name) VALUES ('KHADKA', 'YOGENDRA MR');
INSERT INTO travellers (last_name, first_name) VALUES ('SHIWAKOTI', 'DEVI MAIYA MRS');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'SANDHYA');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'EVAN');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'MANOJ');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'MIN PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'SANCHITA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUTAM', 'SHANTI KUMARI');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BARDAN (CHD)');
INSERT INTO travellers (last_name, first_name) VALUES ('PAUDEL', 'BIRATA (CHD)');
INSERT INTO travellers (last_name, first_name) VALUES ('DAHAL', 'SUJIT');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'KRITIKA');
INSERT INTO travellers (last_name, first_name) VALUES ('MASKEY', 'YASHASWI');
INSERT INTO travellers (last_name, first_name) VALUES ('SARKI', 'RAJ KUMAR MR');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DIKSHYA MS');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'KIRAN MR');
INSERT INTO travellers (last_name, first_name) VALUES ('K C', 'SIJAN MR');
INSERT INTO travellers (last_name, first_name) VALUES ('KHATRI K C', 'SABINA MS');
INSERT INTO travellers (last_name, first_name) VALUES ('NEUPANE', 'SHOVA MS');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'AKRITI MS');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL POKHAREL', 'SMRIDHI MS');
INSERT INTO travellers (last_name, first_name) VALUES ('KHANAL', 'KUSHAL MR');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL', 'DIWASH MR');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL', 'OJASWI MISS');
INSERT INTO travellers (last_name, first_name) VALUES ('POKHAREL', 'OSHIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'STALIN');
INSERT INTO travellers (last_name, first_name) VALUES ('GAUCHAN', 'KAMALA, GAUCHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('KATUWAL CHHETRI', 'RUPESH');
INSERT INTO travellers (last_name, first_name) VALUES ('MASKEY', 'MILAN MITRA');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'ANUSANDHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'BISHNU MAYA');
INSERT INTO travellers (last_name, first_name) VALUES ('GURUNG', 'DURGA BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('RANABHAT', 'ALISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SUNUWAR', 'SHIRJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('BASNET', 'JAY BAHADUR');
INSERT INTO travellers (last_name, first_name) VALUES ('ADHIKARI', 'ANUSANDHAN');
INSERT INTO travellers (last_name, first_name) VALUES ('SHARMA', 'AMRIT');
INSERT INTO travellers (last_name, first_name) VALUES ('TIMILSINA', 'SAGAR MR');
INSERT INTO travellers (last_name, first_name) VALUES ('BHATTARAI', 'ANJU');
INSERT INTO travellers (last_name, first_name) VALUES ('SAPKOTA', 'BISHNU PRASAD');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'ARATI');
INSERT INTO travellers (last_name, first_name) VALUES ('SEN', 'SHIWANI');
INSERT INTO travellers (last_name, first_name) VALUES ('PUN THAPA', 'SRIJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('THAPA', 'PRATIK');
INSERT INTO travellers (last_name, first_name) VALUES ('BASTAKOTI', 'SUDIP');
INSERT INTO travellers (last_name, first_name) VALUES ('RANABHAT', 'ALISH');
INSERT INTO travellers (last_name, first_name) VALUES ('SUNWAR', 'SHRIJANA');
INSERT INTO travellers (last_name, first_name) VALUES ('NAKARMI', 'BINU');
INSERT INTO travellers (last_name, first_name) VALUES ('NAKARMI', 'LAXMI NARAYAN');
INSERT INTO travellers (last_name, first_name) VALUES ('RANABHAT', 'ALISH');