import { ParsedPNR } from "./pnr-parser";
import sharp from "sharp";

// Server-side image generation using SVG + Sharp for PNG conversion
// This avoids ORB/CORB issues with raw SVGs in some browsers and provides better download compatibility

export async function generateTicketPreview(data: ParsedPNR): Promise<Buffer> {
  // Generate a high-quality SVG ticket representation
  const width = 800;
  const height = 400;
  
  const segments = data.segments.map((seg, i) => `
    <g transform="translate(40, ${140 + i * 60})">
      <text x="0" y="0" font-family="Arial" font-size="16" font-weight="bold" fill="#333">${seg.airline_code}${seg.flight_number}</text>
      <text x="100" y="0" font-family="Arial" font-size="16" fill="#666">${seg.departure_airport} ➝ ${seg.arrival_airport}</text>
      <text x="300" y="0" font-family="Arial" font-size="14" fill="#666">${seg.departure_time}</text>
    </g>
  `).join('');

  const passengers = data.passengers.join(', ');

  const svg = `
    <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
      <!-- Background -->
      <rect width="100%" height="100%" fill="#fff" rx="20" ry="20"/>
      <rect width="100%" height="100%" fill="url(#bg-gradient)" rx="20" ry="20" opacity="0.1"/>
      
      <!-- Defs -->
      <defs>
        <linearGradient id="bg-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#3b82f6"/>
          <stop offset="100%" stop-color="#8b5cf6"/>
        </linearGradient>
      </defs>

      <!-- Header -->
      <path d="M0 20C0 8.954 8.954 0 20 0H780C791.046 0 800 8.954 800 20V80H0V20Z" fill="#3b82f6"/>
      <text x="40" y="50" font-family="Arial" font-size="24" font-weight="bold" fill="white">Flight Itinerary</text>
      <text x="760" y="50" font-family="Arial" font-size="18" fill="white" text-anchor="end">${data.pnr_number}</text>

      <!-- Content -->
      <text x="40" y="110" font-family="Arial" font-size="14" fill="#888">PASSENGERS</text>
      <text x="40" y="130" font-family="Arial" font-size="18" font-weight="bold" fill="#333">${passengers}</text>

      <!-- Segments -->
      <g transform="translate(0, 20)">
        ${segments}
      </g>

      <!-- Footer -->
      <line x1="40" y1="340" x2="760" y2="340" stroke="#eee" stroke-width="2" stroke-dasharray="5,5"/>
      <text x="40" y="370" font-family="Arial" font-size="12" fill="#999">Generated by SkyTrips AI • valid for 24h</text>
    </svg>
  `;

  // Convert SVG to PNG Buffer
  const pngBuffer = await sharp(Buffer.from(svg))
    .png()
    .toBuffer();

  return pngBuffer;
}
